Web/TestTemplate/Models/PhanCong.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestTemplate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanCong
    {
        public int MaPC { get; set; }
        public string MaNV { get; set; }
        public string MaCS { get; set; }
        public string GhiChu { get; set; }
    
        public virtual CoSo CoSo { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}

Web/TestTemplate/Areas/Admin/Controllers/PhanCongController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TestTemplate.Models;
using PagedList;

namespace TestTemplate.Areas.Admin.Controllers
{
    [Authorize(Roles = "XemDanhSach")]

    public class PhanCongController : Controller
    {
        // GET: Admin/PhanCong
        QLDSEntities db = new QLDSEntities();
        public ActionResult DanhSachPhanCong(int? page)
        {
            List<PhanCong> dsPhanCongs = db.PhanCongs.ToList();
            //Tạo biến số sản phẩm trên trang
            int PageSize = 6;
            // Tạo biến số trang hiện tại
            int PageNumber = (page ?? 1);
            return View(dsPhanCongs.OrderBy(n => n.MaCS).ToPagedList(PageNumber, PageSize));
        }

        [Authorize(Roles = "Them")]
        public ActionResult ThemMoi()
        {
            return View();
        }

        [HttpPost]
        public ActionResult ThemMoi(PhanCong pc)
        {
            if(string.IsNullOrEmpty(pc.MaCS) == true ||
                string.IsNullOrEmpty(pc.MaNV) == true)
            {
                ModelState.AddModelError("", "Thiếu thông tin");
                return View(pc);
            }

            try
            {
                db.PhanCongs.Add(pc);
                db.SaveChanges();
                return RedirectToAction("DanhSachPhanCong");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View(pc);
            }
        }

        [Authorize(Roles = "Sua")]
        public ActionResult CapNhatPC(int id)
        {
            var pc = db.PhanCongs.Find(id);
            return View(pc);
        }
        [HttpPost]
        public ActionResult CapNhatPC(PhanCong pc)
        {
            if (string.IsNullOrEmpty(pc.MaNV) == true || string.IsNullOrEmpty(pc.MaCS) == true)
            {
                ModelState.AddModelError("", "Thiếu thông tin");
                return View(pc);
            }

            var updatePC = db.PhanCongs.Find(pc.MaPC);
            try
            {
                updatePC.MaNV = pc.MaNV;
                updatePC.MaCS = pc.MaCS;
                updatePC.GhiChu = pc.GhiChu;

                db.SaveChanges();
                return RedirectToAction("DanhSachPhanCong");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View(pc);
            }
        }

        [Authorize(Roles = "Xoa")]
        public ActionResult Xoa(int id)
        {
            var model = db.PhanCongs.Find(id);
            db.PhanCongs.Remove(model);
            db.SaveChanges();
            return RedirectToAction("DanhSachPhanCong");
        }
    }
}

Web/TestTemplate/Areas/Admin/Views/PhanCong/CapNhatPC.cshtml
@model TestTemplate.Models.PhanCong

@{
    ViewBag.Title = "Cập nhật";
    Layout = "~/Areas/Admin/Views/Shared/LayoutAdmin.cshtml";
}

<h2>Cập nhật</h2>


@using (Html.BeginForm("CapNhatPC", "PhanCong", FormMethod.Post))
{
    @Html.HiddenFor(model => model.MaPC)
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            <label class="control-label col-md-10 " style="margin-top: 10px">Mã nhân viên</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaNV, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaNV, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
                <label class="control-label col-md-10 " style="margin-top: 10px">Mã cơ sở</label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.MaCS, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.MaCS, "", new { @class = "text-danger" })
                </div>
            </div>

        <div class="form-group">
            <label class="control-label col-md-10 " style="margin-top: 10px">Ghi chú</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.GhiChu, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GhiChu, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Cập nhật" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

Web/TestTemplate/Areas/Admin/Views/PhanCong/DanhSachPhanCong.cshtml
@using PagedList.Mvc;
@model PagedList.IPagedList<TestTemplate.Models.PhanCong>

@{
    ViewBag.Title = "Danh sách phân công";
    Layout = "~/Areas/Admin/Views/Shared/LayoutAdmin.cshtml";
    TestTemplate.Models.QLDSEntities db = new TestTemplate.Models.QLDSEntities();
}

<h2>Danh sách phân công</h2>
<p style="font-size: 16px; font-weight:bold; color:red">
    <a href="@Url.Action("ThemMoi", "PhanCong", new { area = "Admin" })">Thêm mới</a>
</p>

<table class="table">
    <tr>
        <th>
            <label class="control-label col-md-10 ">Mã nhân viên</label>
        </th>
        <th>
            <label class="control-label col-md-10 ">Họ tên</label>
        </th>
        <th>
            <label class="control-label col-md-10 ">Tên cơ sở</label>
        </th>
        <th>
            <label class="control-label col-md-10 ">Ghi chú</label>
        </th>
        <th>
            <label class="control-label col-md-10 ">Cập nhật</label>
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td style="padding: 0px 30px">
                @Html.DisplayFor(modelItem => item.MaNV)
            </td>
            <td>
                @foreach (var nv in db.NhanViens.Where(n => n.MaNV == item.MaNV).ToList())
                {
                    @nv.HoTen
                }
            </td>
            <td>
                @foreach (var cs in db.CoSoes.Where(n => n.MaCS == item.MaCS).ToList())
                {
                    @cs.TenCS
                }
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GhiChu)
            </td>
            <td>
                @Html.ActionLink("Chỉnh sửa", "CapNhatPC", new { id = item.MaPC }) |
                @Html.ActionLink("Xóa", "Xoa", new { id = item.MaPC })
            </td>
        </tr>
    }
</table>
<div class="dlink">
    @Html.PagedListPager(Model, page => Url.Action("DanhSachPhanCong", new { page = page }))
</div>

Web/TestTemplate/Areas/Admin/Views/PhanCong/ThemMoi.cshtml
@model TestTemplate.Models.PhanCong

@{
    ViewBag.Title = "Thêm mới";
    Layout = "~/Areas/Admin/Views/Shared/LayoutAdmin.cshtml";
}

<h2>Thêm mới</h2>


@using (Html.BeginForm("ThemMoi", "PhanCong", FormMethod.Post)) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <label class="control-label col-md-10 " style="margin-top: 10px">Mã nhân viên</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaNV, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaNV, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-10 " style="margin-top: 10px">Mã cơ sở</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaCS, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaCS, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-10 " style="margin-top: 10px">Ghi chú</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.GhiChu, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GhiChu, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Thêm" class="btn btn-primary" />
            </div>
        </div>
    </div>
}