Web/TestTemplate/Areas/Admin/Controllers/CoSoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TestTemplate.Models;
using PagedList;

namespace TestTemplate.Areas.Admin.Controllers
{
    [Authorize(Roles = "XemDanhSach")]
    public class CoSoController : Controller
    {
        // GET: Admin/CoSo
        QLDSEntities db = new QLDSEntities();

        public ActionResult DanhSachCoSo(int? page)
        {
            List<CoSo> danhSachCoSo = db.CoSoes.ToList();
            //Tạo biến số sản phẩm trên trang
            int PageSize = 6;
            // Tạo biến số trang hiện tại
            int PageNumber = (page ?? 1);
            return View(danhSachCoSo.OrderBy(n => n.MaCS).ToPagedList(PageNumber, PageSize));
        }

        [Authorize(Roles = "Them")]
        public ActionResult ThemMoi()
        {
            return View();
        }

        [HttpPost]
        public ActionResult ThemMoi(CoSo model, HttpPostedFileBase fileAnh)
        {
            if (fileAnh.ContentLength > 0)
            {
                string rootFolder = Server.MapPath("/Content/img/");
                string pathImage = rootFolder + fileAnh.FileName;
                fileAnh.SaveAs(pathImage);
                model.HinhAnh = fileAnh.FileName;
            }

            if (string.IsNullOrEmpty(model.MaCS) == true || string.IsNullOrEmpty(model.TenCS) == true ||
                string.IsNullOrEmpty(model.HinhAnh) == true || string.IsNullOrEmpty(model.LinkMap) == true ||
                    string.IsNullOrEmpty(model.MucGia) == true || string.IsNullOrEmpty(model.DiaChi) == true)
            {
                ModelState.AddModelError("", "Thiếu thông tin");
                return View(model);
            }

           
            try
            {
                db.CoSoes.Add(model);
                db.SaveChanges();
                return RedirectToAction("DanhSachCoSo");
            }
            catch(Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View(model);
            }
        }

        [Authorize(Roles = "Sua")]
        public ActionResult CapNhat(string id)
        {
            var model_Edit = db.CoSoes.Find(id);
            return View(model_Edit);
        }

        [HttpPost]
        public ActionResult CapNhat(CoSo model_Edit, HttpPostedFileBase fileAnh)
        {
            if (fileAnh.ContentLength > 0)
            {
                string rootFolder = Server.MapPath("/Content/img/");
                string pathImage = rootFolder + fileAnh.FileName;
                fileAnh.SaveAs(pathImage);
                model_Edit.HinhAnh = fileAnh.FileName;
            }

            if (string.IsNullOrEmpty(model_Edit.TenCS) == true ||
                string.IsNullOrEmpty(model_Edit.HinhAnh) == true || string.IsNullOrEmpty(model_Edit.LinkMap) == true ||
                    string.IsNullOrEmpty(model_Edit.MucGia) == true || string.IsNullOrEmpty(model_Edit.DiaChi) == true)
            {
                ModelState.AddModelError("", "Thiếu thông tin");
                return View(model_Edit);
            }

            var updateCoSo = db.CoSoes.Find(model_Edit.MaCS);
            try
            {
                updateCoSo.TenCS = model_Edit.TenCS;
                updateCoSo.HinhAnh = model_Edit.HinhAnh;
                updateCoSo.DiaChi = model_Edit.DiaChi;
                updateCoSo.LinkMap = model_Edit.LinkMap;
                updateCoSo.MucGia = model_Edit.MucGia;
                updateCoSo.MaLoaiCS = model_Edit.MaLoaiCS;

                db.SaveChanges();
                return RedirectToAction("DanhSachCoSo");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View(model_Edit);
            }
        }

        [Authorize(Roles = "Xoa")]
        public ActionResult Xoa(string id)
        {
            var model = db.CoSoes.Find(id);
            db.CoSoes.Remove(model);
            db.SaveChanges();
            return RedirectToAction("DanhSachCoSo");
        }
    }
}

Web/TestTemplate/Controllers/CoSoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TestTemplate.Models;

namespace TestTemplate.Controllers
{
    public class CoSoController : Controller
    {
        // GET: CoSo
        QLDSEntities db = new QLDSEntities();
        [ChildActionOnly] // người dùng không thể get partial
        public ActionResult CoSoBongDaPartial()
        {

            return PartialView();
        }

            [ChildActionOnly] // người dùng không thể get partial
            public ActionResult CoSoBongRoPartial()
        {

            return PartialView();
        }

        [ChildActionOnly] // người dùng không thể get partial
        public ActionResult CoSoCauLongPartial()
        {

            return PartialView();
        }

        [ChildActionOnly] // người dùng không thể get partial
        public ActionResult CoSoTennisPartial()
        {

            return PartialView();
        }
    }
}

Web/TestTemplate/Areas/Admin/Views/CoSo/CapNhat.cshtml
@model TestTemplate.Models.CoSo

@{
    ViewBag.Title = "Cập nhật cơ sở";
    Layout = "~/Areas/Admin/Views/Shared/LayoutAdmin.cshtml";
    TestTemplate.Models.QLDSEntities db = new TestTemplate.Models.QLDSEntities();
}

<h2>Cập nhật</h2>

@using (Html.BeginForm("CapNhat", "CoSo", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <!--lấy ra đối tượng cần cập nhật-->
    @Html.HiddenFor(m => m.MaCS)
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        <label class="control-label col-md-10 " style="margin-top: 10px">Mã cơ sở</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.MaCS, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.MaCS, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-10 " style="margin-top: 10px">Tên cơ sở</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.TenCS, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TenCS, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-10 " style="margin-top: 10px">Hình ảnh</label>
        <div class="col-md-10">
            <input type="file" name="FileAnh" />
            @Html.ValidationMessageFor(model => model.HinhAnh, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-10 " style="margin-top: 10px">Địa chỉ</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-10 " style="margin-top: 10px">Link google maps</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.LinkMap, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.LinkMap, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-10 " style="margin-top: 10px">Mức giá</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.MucGia, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.MucGia, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-10 " style="margin-top: 10px">Mã loại sân</label>
        <div class="col-md-10">
            <select name="MaLs" class="form-control">
                @foreach (var loai in db.LoaiCoSoes.ToList())
                {
                    <option value="@loai.MaLoaiCS">@loai.TenLoaiCS</option>
                }
                @*<option value="BongDa">f</option>
                    <option value="BongRo">br</option>
                    <option value="CauLong">bmt</option>
                    <option value="Tennis">tennis   </option>*@
            </select>
            @Html.ValidationMessageFor(model => model.MaLoaiCS, "", new { @class = "text-danger" })
        </div>
    </div>



    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Cập nhật" class="btn btn-primary" />
        </div>
    </div>
</div>
}

Web/TestTemplate/Areas/Admin/Views/CoSo/DanhSachCoSo.cshtml
@using PagedList.Mvc;

@model PagedList.IPagedList<TestTemplate.Models.CoSo>

@{
    ViewBag.Title = "DanhSachCoSo";
    Layout = "~/Areas/Admin/Views/Shared/LayoutAdmin.cshtml";
    //Khởi tạo control WebGrid
    //  WebGrid grid = new WebGrid(source: Model, rowsPerPage: 10);
}

<h2>Danh sách cơ sở</h2>
<p>
    <a href="@Url.Action("ThemMoi", "CoSo", new { area = "Admin" })">Thêm mới</a>
</p>

@* Thể hiện dữ liệu thông qua control WebGrid *@
@*@grid.GetHtml(
    tableStyle: "gridTable",
    headerStyle: "gridHead",
    footerStyle: "gridFooter",
    rowStyle: "gridRow",
    alternatingRowStyle: "gridAltRow",
    columns: grid.Columns(
        grid.Column(),
        grid.Column(),
        grid.Column(),) 
    )*@
<table class="table table-bordered">
    <tr>
        <th>
            <label class="control-label col-md-10 ">Tên cơ sở</label>
        </th>
        <th>
            <label class="control-label col-md-10 ">Hình ảnh</label>
        </th>
        <th>
            <label class="control-label col-md-10 ">Địa chỉ</label>
        </th>
        <th>
            <label class="control-label col-md-10 ">Maps</label>
        </th>
        <th>
            <label class="control-label col-md-10 ">Loại sân</label>
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.TenCS)
            </td>
            <td>
                <img class="img-responsive" src="@Url.Content("~/Content/img/" + item.HinhAnh)" alt="" />
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DiaChi)
            </td>
            <td style="word-break: break-word;">
                @Html.DisplayFor(modelItem => item.LinkMap)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LoaiCoSo.TenLoaiCS)
            </td>
            <td>
                @Html.ActionLink("Cập nhật", "CapNhat", new { id = item.MaCS }) |
                @Html.ActionLink("Xóa", "Xoa", new { id = item.MaCS })
            </td>
        </tr>
    }

</table>
<div class="dlink">
    @Html.PagedListPager(Model, page => Url.Action("DanhSachCoSo", new { page = page }))
</div>

Web/TestTemplate/Areas/Admin/Views/CoSo/ThemMoi.cshtml
@model TestTemplate.Models.CoSo

@{
    ViewBag.Title = "Thêm cơ sở";
    Layout = "~/Areas/Admin/Views/Shared/LayoutAdmin.cshtml";
    TestTemplate.Models.QLDSEntities db = new TestTemplate.Models.QLDSEntities();
}

<h2>Thêm</h2>

@using (Html.BeginForm("ThemMoi","CoSo", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        <label class="control-label col-md-10 " style="margin-top: 10px">Mã cơ sở</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.MaCS, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.MaCS, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-10 " style="margin-top: 10px">Tên cơ sở</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.TenCS, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TenCS, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-10 " style="margin-top: 10px">Hình ảnh</label>
        <div class="col-md-10">
            <input type="file" name="FileAnh" />
            @Html.ValidationMessageFor(model => model.HinhAnh, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-10 " style="margin-top: 10px">Địa chỉ</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-10 " style="margin-top: 10px">Link google maps</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.LinkMap, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.LinkMap, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-10 " style="margin-top: 10px">Mức giá</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.MucGia, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.MucGia, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-10 " style="margin-top: 10px">Tên loại sân</label>
        <div class="col-md-10">
            <select name="MaLs" class="form-control">
                @foreach(var loai in db.LoaiCoSoes.ToList())
                {
                    <option value="@loai.MaLoaiCS">@loai.TenLoaiCS</option>
                }
                @*<option value="BongDa">f</option>
                <option value="BongRo">br</option>
                <option value="CauLong">bmt</option>
                <option value="Tennis">tennis   </option>*@
            </select>
            @Html.ValidationMessageFor(model => model.MaLoaiCS, "", new { @class = "text-danger" })
        </div>
    </div>



    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Thêm" class="btn btn-primary" />
        </div>
    </div>
</div>
}